version: 2.1
orbs:
  slack: circleci/slack@4.3.3

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - northwind-pg-data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - "5432:5432"
    notify:
      steps:
        - slack/notify:
          template: basic_fail_1



volumes:
  northwind-pg-data:
    external: true
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets 
#