version: 2.1
orbs:
  slack: circleci/slack@4.3.3

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - northwind-pg-data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - "5432:5432"
    notify:
      steps:
        - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
        event: always
        - slack/status:
          failure_message: ':red_circle: ${CIRCLE_JOB} Failed! Branch: ${CIRCLE_BRANCH}, Message: ${GIT_COMMIT_DESC}'
          success_message: ':tada: ${CIRCLE_JOB} Succeeded! Branch: ${CIRCLE_BRANCH}, Message: ${GIT_COMMIT_DESC}'
          webhook: ${SLACK_WEBHOOK}


volumes:
  northwind-pg-data:
    external: true
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets 
## ADDED default channel from  copy link  option
## added slack secrets to to context.. i think
# CHANGED SLACK_ACCESS_TOKEN TO SIGNING SECRET -- WHO KNOWS