version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
   steps:
      - run: exit 0
      - slack/status:
          fail_only: false
          mentions: 'USERID1,USERID2'
          only_for_branches: only_for_branches
          webhook: SLACK_WEBHOOK
workflows:
  send-notification:
    jobs:
      - notify:
          context: 'slack handshake'
