version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      # When there is a successful deployment, send a notification with a different template.
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

  workflows:
  send-notification:
    jobs:
      - notify:
          context: slack handshake
