version: '2.1'
orbs:
  slack: circleci/slack@4.1
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: '#docker-slack-notifications'
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
workflows:
  default:
    jobs:
      - notify:
          context: 'slack handshake'
#ADDED NEW WEBHOOK AS WELL AS PERMISSION FOR IT, I THINK...

#added scopes